name: 🧠 AI Bugfix Suggestie

on:
  workflow_dispatch:

jobs:
  ai-bugfix:
    runs-on: ubuntu-latest
    env:
      OPENAI_ENDPOINT: https://<jouw-endpoint>.openai.azure.com
      DEPLOYMENT_NAME: gpt4o-devops
      API_VERSION: 2024-05-01

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Lees testbestand
      id: testfile
      run: |
        content=$(base64 -w 0 tests/TestInvoiceService.cs)
        echo "content=$content" >> "$GITHUB_OUTPUT"

    - name: Roep GPT-4o aan voor suggestie
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        json=$(jq -n           --arg c "${{ steps.testfile.outputs.content }}"           '{
            messages: [
              { "role": "system", "content": "Je bent een .NET C# expert" },
              { "role": "user", "content": "Analyseer deze test en geef een bugfix. Base64 testbestand: \($c)" }
            ],
            temperature: 0.3,
            max_tokens: 1200
          }')

        curl -s -X POST "${OPENAI_ENDPOINT}/openai/deployments/${DEPLOYMENT_NAME}/chat/completions?api-version=${API_VERSION}"           -H "Content-Type: application/json"           -H "api-key: ${OPENAI_API_KEY}"           -d "$json" | jq -r '.choices[0].message.content'
